app = "kafka"

[[services]]
internal_port = 9092
protocol = "tcp"

[[services.ports]]
port = 9092

[[services.tcp_checks]]
interval = "15s"
timeout = "2s"
grace_period = "180s"

[[services]]
internal_port = 2181
protocol = "tcp"

[[services.ports]]
port = 2181
